INSERT INTO PRODUCTS (ID, NAME, DESCRIPTION, PRICE) VALUES ('1', 'product_1', 'product_1', 1.0);
INSERT INTO PRODUCTS (ID, NAME, DESCRIPTION, PRICE) VALUES ('2', 'product_2', 'product_2', 2.0);
INSERT INTO PRODUCTS (ID, NAME, DESCRIPTION, PRICE) VALUES ('3', 'product_3', 'product_3', 3.0);
INSERT INTO PRODUCTS (ID, NAME, DESCRIPTION, PRICE) VALUES ('4', 'product_4', 'product_4', 4.0);